version: "3.9"

services:
  db:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_DATABASE: Products-db
    ports:
      - "27017:27017"

 api:
   build: .
   env_file: .env
   command: bash -c "alembic upgrade head && uvicorn app:app --reload"
   volumes:
     - .:/code
   ports:
     - "127.0.0.1:8000:8000"
   depends_on:
     - db